name: Update README with Medium Articles

on:
  schedule:
    - cron: '0 * * * *' # 每小時執行一次
  workflow_dispatch: # 允許手動觸發

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
      - name: Install dependencies
        run: npm install rss-parser
      - name: Update README
        run: node updateReadme.js
      - name: Commit and push changes
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config --global user.email "show81728@gmail.com"
          git config --global user.name "Billy-Ti"
          git add README.md
          git commit -m "Update README posts" || exit 0  
          git push --set-upstream https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} main
